package model.enums;

/**
 * A logical representation of a view panel
 *
 */
public enum ApplicationState {

	HOME, REVIEWER_OVERVIEW, THESES_OVERVIEW, REVIEWER_EDITOR, STATE_CHOOSER,
	THESIS_ASSIGNMENT, FIRSTREVIEWER_IMPORT, COLLABORATION_TABLE, COLLABORATION_PIECHART

}
