package model.enums;

public enum ViewId { // TODO rename these so that its more believable that this is a unique id? Or
						// maybe even remove this class?
	HOME, OVERVIEW_TABLE, THESES_OVERVIEW, ACTIONS, EDITOR, STATE_CHOOSER, STATE_BUTTONS, THESIS_ASSIGNMENT,
	FIRSTREVIEWER_IMPORT, COLLABORATION_OVERVIEW, COLLABORATION_OPTIONS, COLLABORATION_CHOOSE_DATA,
	COLLABORATION_CHOOSE_PRESENTATION;
}
